package request;

public enum RequestType {
    LOGIN,
    CAPTCHA,
    ADMIN_DATA,
    NEW_MESSAGE,
    CHECK_CONNECTION,
    MOHSENI_DATA,
    STUDENT_DATA,
    MASTER_DATA,
    SINGLE_STUDENT,
    GET_TIME,
    CHANGE_PHONE,
    CHANGE_EMAIL,
    CHANGE_PASS,
    DELETE_COURSE,
    DELETE_MASTER,
    ADD_COURSE,
    EDIT_COURSE,
    ADD_STUDENT,
    ADD_MASTER,
    EDIT_MASTER,
    NEW_PROTEST
}
